export const FETCH_ALL_PRODUCT = 'FETCH_ALL_PRODUCT';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DECREMENT_PRODUCT_CART = 'DECREMENT_PRODUCT_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const SET_COUNT_CART = 'SET_COUNT_CART';
export const SET_CART_TOTAL_PRICE = 'SET_CART_TOTAL_PRICE';